services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Chemege1.
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - delivery_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test_db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Chemege1.
      POSTGRES_DB: test_db
    ports:
      - "5433:5433"
    networks:
      - delivery_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - delivery_network
    ports:
      - "8080:8080"

networks:
  delivery_network:
    driver: bridge
